
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

ENCODER_ENABLE = yes

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no

